name: dados_de_motores_eletricos
publish_to: 'none'

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.9
  shared_preferences: ^2.5.3
  file_picker: ^10.3.10
  cupertino_icons: ^1.0.8